# Generated by Django 5.2.6 on 2025-09-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
