# Generated by Django 5.2.6 on 2025-09-29 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_temperature_humidity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='value',
            new_name='temperature',
        ),
    ]
