# Generated by Django 5.2 on 2025-09-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_rename_value_temperature_temperature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperature",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
