# Generated by Django 5.2.6 on 2025-10-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_remove_temperature_unique_location_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for the device (e.g., 'Living Room Sensor')",
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Room/location name (e.g., 'Living Room')",
                        max_length=100,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("switchbot", "SwitchBot Meter"),
                            ("govee", "Govee Thermometer"),
                            ("manual", "Manual Entry"),
                        ],
                        default="switchbot",
                        max_length=20,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        help_text="Device MAC address or identifier",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to monitor this device"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["location", "name"],
            },
        ),
    ]
