# Generated by Django 5.2.6 on 2025-10-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_add_simple_device_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Device MAC address or identifier (required for SwitchBot/Govee devices)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
